### ISSUE TITLE
License Expiration In the past

### ISSUE THREAD

**Issue by caraya** [Monotype/Monotype_prototype_variable_fonts#10]
The license for Avenir is set to expire 12/31/18. If this is the case then we cannot use the font for testing and experiment. 

Will you change this or is this permanent now that Avenir has been released commercially?

**Comment by taylorb-monotype** [comment]
Thank you for pointing out that the license has expired. We will remove these fonts. Please check with MyFonts.com for information on how to purchase licenses for Avenir Next and other variable fonts.
