### ISSUE TITLE
Overlap in the "A"

### ISSUE THREAD

**Issue by RoelN** [Monotype/Monotype_prototype_variable_fonts#2]
![screenshot](https://cloud.githubusercontent.com/assets/4570664/21758309/a96d81c8-d63a-11e6-9a18-14e72c2ecafb.png)

This is on Mac OS X, El Capitan in Chrome 55 and Firefox 50.

**Comment by TrueTyper** [comment]
This is a rendering bug in El Capitan which is address in macOS Sierra. Please try the font in Sierra with the Webkit nightly build to see proper rendering.
