### ISSUE TITLE
Inconsistent names (family, full)

### ISSUE THREAD

**Issue by PeterCon** [Monotype/Monotype_prototype_variable_fonts#3]
Thanks for posting this variable font!

There's an inconsistency in names:

1 (Family): "Avenir Next Variable"
2 (Subfamily): "Regular"
4 (full): "Avenir Next Variable Regular harmonized"

Name ID 4 should be the concatenation of 1 and 2, with the possible exception that "Regular" can be omitted. So, based on 1 and 2, I would expect 4 to be "Avenir Next Variable Regular" or "Avenir Next Variable".

16 (preferred family): "Avenir Next"
17 (preferred subfamily): "Regular"

In this case, 2 and 17 are the same (and the string data is not duplicated), which is good. But 1 and 16 are different. They should be the same.

**Comment by taylorb-monotype** [comment]
Thanks Peter. Resolved.
