### ISSUE TITLE
STAT table should have axis value tables

### ISSUE THREAD

**Issue by PeterCon** [Monotype/Monotype_prototype_variable_fonts#5]
There's no reason for this font not to have axis value tables within the STAT table for the following:
wght, 400, name ID 17 ("Regular"), elidable
wght, 500, name ID 259 ("Medium")
wght, 700, name ID 260 ("Bold")
wght, 900, name ID 261 ("Heavy")
wdth, 100, name ID 17 ("Regular"), elidable
wdth, 75, name ID 262 ("Condensed")

**Comment by taylorb-monotype** [comment]
Agree. Thanks. Resolved in latest version.
